/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manualSidebar: [{ type: 'autogenerated', dirName: '.' }, { type: 'link', label: 'Tags', href: '/docs/tags'}],
};

module.exports = sidebars;
